### PR TITLE
first spelling error

### PR DESCRIPTION
**Pull request by gurkpet**
Please check the readme for spelling errors, if you feel that all the errors are covered review with your name.

When all 3 of you have checked for errors and feel everything is ok then we can rebase.

### CODE REVIEW

**Review by yuqizhu — CHANGES_REQUESTED** [review]
23: JSDocs is

**Review by yuqizhu — COMMENTED** [review]
53: an API folder  
53: for for your API 
120: will be rendered
132: might not want or need  sounds repeating

**Review by trivediu — APPROVED** [review]
Approved by Uday

**Comment by mcsteezy** [comment]
55: 'ang' should be 'any'

**Review by yuqizhu — COMMENTED** [review]
136: The first sentence  
136: current directory and any..
138: may not have been parsed => have not been parsed
142 first sentence doesn't sound right to me
154 it's

**Review by yuqizhu — APPROVED** [review]

**Review by trivediu — APPROVED** [review]
approved - Uday

**Pull request merged**
